export const FETCH_COLLECTION_REQUEST = 'FETCH_COLLECTION_REQUEST'
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS'

export const UPDATE_COLLECTIONS_REQUEST = 'ADD_COLLECTION_SEND'
export const ADD_COLLECTION_SUCCESS = 'ADD_COLLECTION_SUCCESS'
export const EDIT_COLLECTION_SUCCESS = 'EDIT_COLLECTION_SUCCESS'
