export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS'
export const GET_OFFERS_REQUEST = 'GET_OFFERS_REQUEST'

export const ADD_OFFER_SEND = 'ADD_OFFER_SEND'
export const ADD_OFFER_SUCCESS = 'ADD_OFFER_SUCCESS'

