export const FETCH_SEGMENTS_REQUEST = 'FETCH_SEGMENTS_REQUEST'
export const FETCH_SEGMENTS_SUCCESS = 'FETCH_SEGMENTS_SUCCESS'

export const UPDATE_SEGMENT_REQUEST = 'UPDATE_SEGMENT_REQUEST'
export const UPDATE_SEGMENT_SUCCESS = 'UPDATE_SEGMENT_SUCCESS'